# Generated by Django 4.1.7 on 2023-02-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papeleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_unico_identificacion', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papeleta.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papeleta.oficial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papeleta.persona')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papeleta.vehiculo')),
            ],
        ),
    ]
