# Generated by Django 4.1.7 on 2023-02-17 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papeleta', '0002_oficial_vehiculo_papeleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeleta',
            name='comentarios',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='papeleta',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
