# Generated by Django 4.1.7 on 2023-02-19 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='credential_application',
            field=models.OneToOneField(db_column='credential_application_id', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='identification_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'Solo 8 caracteres numÃ©ricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification_document',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'Solo 8 caracteres numÃ©ricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='patent_plate',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{6}$', 'Solo 6 caracteres alphanumericos son permitidos.')]),
        ),
    ]
